// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_wLBi8oxEGiLNLB-ufU0XvnELoJtpUQ',
    appId: '1:812334187946:web:ff0aee1d6cd38331f9d7d3',
    messagingSenderId: '812334187946',
    projectId: 'salat26e',
    authDomain: 'salat26e.firebaseapp.com',
    storageBucket: 'salat26e.appspot.com',
    measurementId: 'G-PLHWHZV804',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgcMph40Rumspa9SKi9A9bRdUaNxzwcM',
    appId: '1:812334187946:android:0891582185d8bebcf9d7d3',
    messagingSenderId: '812334187946',
    projectId: 'salat26e',
    storageBucket: 'salat26e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxlX1epm7t6zzACPhOud2zWPC0fSdewa8',
    appId: '1:812334187946:ios:f47568bef975d783f9d7d3',
    messagingSenderId: '812334187946',
    projectId: 'salat26e',
    storageBucket: 'salat26e.appspot.com',
    iosBundleId: 'com.example.salahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxlX1epm7t6zzACPhOud2zWPC0fSdewa8',
    appId: '1:812334187946:ios:f47568bef975d783f9d7d3',
    messagingSenderId: '812334187946',
    projectId: 'salat26e',
    storageBucket: 'salat26e.appspot.com',
    iosBundleId: 'com.example.salahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0_wLBi8oxEGiLNLB-ufU0XvnELoJtpUQ',
    appId: '1:812334187946:web:bb95e2324f8c4805f9d7d3',
    messagingSenderId: '812334187946',
    projectId: 'salat26e',
    authDomain: 'salat26e.firebaseapp.com',
    storageBucket: 'salat26e.appspot.com',
    measurementId: 'G-HMELXFZLZX',
  );
}
